image: registry.gitlab.com/chromaway/core-tools/chromia-images/maven-docker:1.0.0

.setup:
  tags:
    - saas-linux-large-amd64
  before_script:
    - docker run
      --detach
      --name postgres
      --env POSTGRES_PASSWORD=postchain
      --env POSTGRES_USER=postchain
      --env PGDATA=/pgtmpfs
      --tmpfs=/pgtmpfs:size=1000m
      --publish 5432:5432
      postgres:14.7-alpine3.17
  artifacts:
    when: always
    reports:
      junit:
        - "*/target/surefire-reports/TEST-*.xml"
        - "*/target/failsafe-reports/TEST-*.xml"
    expire_in: 1 week

stages:
  - build
  - deploy
  - dependency-check

deploy:
  extends: .setup
  stage: deploy
  only:
    - master
    - dev
    - /^version-[0-9]+[.][0-9]+([.][0-9]+)?$/
  script:
    - mvn $MAVEN_CLI_OPTS source:jar deploy

build:
  extends: .setup
  stage: build
  except:
    - master
    - dev
    - /^version-[0-9]+[.][0-9]+([.][0-9]+)?$/
  script:
    - mvn $MAVEN_CLI_OPTS verify

dependency-check:
  extends: .setup
  stage: dependency-check
  interruptible: true
  script:
    - mvn $MAVEN_CLI_OPTS --activate-profiles dependency-check verify
  only:
    variables:
      - $RUN_DEPENDENCY_CHECK == "true"

variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -s .gitlab-settings.xml -U"
  POSTCHAIN_DB_URL: jdbc:postgresql://docker/postchain
  DOCKER_HOST: tcp://docker:2375

services:
  - name: docker:23.0.4-dind
    alias: docker
    # explicitly disable tls to avoid docker startup interruption
    command: [ "--tls=false" , "--experimental" ]

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository
